SUPABASE_URL = "https://budqjymmietmbhsvdpso.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1ZHFqeW1taWV0bWJoc3ZkcHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NjA4NjYsImV4cCI6MjA3NTMzNjg2Nn0.tkrcNf-IcoMAHMEcSFkctqz6me5WbScAuqKlBddnCzY"
